name: Modern AlkaMe
favicon: null
layout_spectrum: 0.5633727
typography_spectrum: 0.76644
title: Modern AlkaMe
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eae9e7'
    - '#c2bbb8'
    - '#424853'
    - '#0073df'
  brandStrength: 0.4860365
  lightness: 0.8630504
  saturation: 0.5343716
  rhythmicContrast: 0.3904404
purpose: []
