typography_spectrum: 0.4113806
color:
  saturation: 0.7574627
  brandStrength: 0.5107276
  lightness: 0.8465485
  brandColors:
    - '#0F1217'
    - '#1F262C'
    - '#343E47'
    - '#5E727D'
    - '#738A99'
  rhythmicContrast: 0.65625
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9109142
analytics:
  twitter: null
  google: null
  facebook: null
name: Modern AlkaMe
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About Us
    id: dba34c46-4f4d-4b02-90fb-10121399436b
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Modern AlkaMe
description: Next Generation Cognitive Supplements
purpose: []
