layout_spectrum: 1
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.1627282
  brandStrength: 0.490333
  lightness: 0.6997852
  brandColors:
    - '#FFFFFF'
    - '#89D0EE'
    - '#F06522'
    - '#F6AA86'
    - '#26A9E1'
  rhythmicContrast: 0.7975295
typography_spectrum: 0.4076262
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Modern AlkaMe
